export const INITIAL_QUEST_DATA = [
  {
    category: "First Test",
    questions: [
      {
        question: "R is technically much closer to the Scheme language than it is to the original _____ language",
        options: ["B", "C", "C++", "S"],
        correctAnswer: 3
      },
      {
        question: "Which of the following describes R language?",
        options: ["Free", "Paid", "Available for free trial only", "Testing"],
        correctAnswer: 0
      },
      {
        question: "In 1991, R was created by Ross Ihaka and Robert Gentleman in the Department of Statistics at the University of _________",
        options: ["John Hopkins", "California", "Harvard", "Auckland"],
        correctAnswer: 3
      },
      {
        question: "R runs on the ____________ operating system.",
        options: ["Linux", "Windows", "Ubuntu", "Any operating system"],
        correctAnswer: 3
      },
      {
        question: "You can download “base” R system from _________",
        options: ["A", "B", "CRAN", "D"],
        correctAnswer: 2
      },
      {
        question: "Which of the following command is used to print an object “x” in R?",
        options: ["printf(x)", "print(x)", "printx", "print[x]"],
        correctAnswer: 1
      },
      {
        question: "Which of the following is used for Statistical analysis in R language?",
        options: ["RStudio", "Studio", "Heck", "KStudio"],
        correctAnswer: 0
      },
      {
        question: "Point out the correct statement?",
        options: [
          "rep() is be used for replicating an object in various complicated ways",
          "seq() function has four arguments",
          "sequence() is a more general facility for generating sequences",
          "numerical vectors are generated by conditions"
        ],
        correctAnswer: 0
      },
      {
        question: "Which of the following finds the position of a quantile in a dataset?",
        options: ["quantile()", "barplot()", "barchart()", "rep()"],
        correctAnswer: 0
      },
      {
        question: "Which of the following code create n samples of size “size” with probability prob from the binomial?",
        options: [
          "z <- rinom(n,size,pro)",
          "z <- rbinom(n,size,pro)",
          "z <- binom(n,size,pro)",
          "z >- nom(n,size,pro)"
        ],
        correctAnswer: 1
      },
      {
        question: "What is the simplest way of creating the vector?",
        options: ["C function", "Create", "Destroy", "Invalid"],
        correctAnswer: 0
      },
      {
        question: "Which function replicates elements of vectors?",
        options: ["C", "Rep", "Crep", "Grep"],
        correctAnswer: 1
      },
      {
        question: "To bind a row onto an already existing matrix, the ______ function can be used.",
        options: ["rbind", "Sbnd", "Gbind", "Sbind"],
        correctAnswer: 0
      },
      {
        question: "Which of the following extracts first element of the vector x?",
        options: ["x[10]", "x[1]", "x[0]", "x[2]"],
        correctAnswer: 1
      },
      {
        question: "Two vectors N1 and N2 are defined as N1 = c(3, 2, 4) and N2 = c(1, 2). What will be the output of vector Z that is defined as N1*N2.",
        options: ["(3, 2, 4)", "(3, 6, 4)", "(3, 4, 5)", "(3, 4, 4)"],
        correctAnswer: 3
      },
      {
        question: "__________ can contain heterogeneous inputs.",
        options: ["Matrix", "Data Frames", "Matrix and Data Frames", "Does not exists"],
        correctAnswer: 1
      },
      {
        question: "R is mostly used in ______________",
        options: ["Problem solving", "Statistics", "Probability", "All of the mentioned"],
        correctAnswer: 3
      },
      {
        question: "What is the meaning of “<-“?",
        options: ["Functions", "Loops", "Addition", "Assignment"],
        correctAnswer: 3
      },
      {
        question: "In the expression x <- 4 in R, what is the class of ‘x’ as determined by the `class()’ function?",
        options: ["Character", "Numeric", "Integer", "Word"],
        correctAnswer: 2
      },
      {
        question: "Accessing elements is achieved through a process called ________",
        options: ["Indexing", "Outdexing", "Highlighting", "Scrapping"],
        correctAnswer: 0
      }
    ]
  }
];
