export const PDF_QUESTIONS = [
  {
    question: "R is technically much closer to the Scheme language than it is to the original _____ language",
    options: ["B", "C", "C++", "S"],
    correctAnswer: 3
  },
  {
    question: "Which of the following describes R language?",
    options: ["Free", "Paid", "Available for free trial only", "Testing"],
    correctAnswer: 0
  },
  {
    question: "In 1991, R was created by Ross Ihaka and Robert Gentleman in the Department of Statistics at the University of _________",
    options: ["John Hopkins", "California", "Harvard", "Auckland"],
    correctAnswer: 3
  },
  {
    question: "R runs on the ____________ operating system.",
    options: ["Linux", "Windows", "Ubuntu", "Any operating system"],
    correctAnswer: 3
  },
  {
    question: "You can download “base” R system from _________",
    options: ["A", "B", "CRAN", "D"],
    correctAnswer: 2
  },
  {
    question: "Which of the following command is used to print an object “x” in R?",
    options: ["printf(x)", "print(x)", "printx", "print[x]"],
    correctAnswer: 1
  },
  {
    question: "Which of the following is used for Statistical analysis in R language?",
    options: ["RStudio", "Studio", "Heck", "KStudio"],
    correctAnswer: 0
  },
  {
    question: "Point out the correct statement?",
    options: ["rep() is be used for replicating an object in various complicated ways", "seq() function has four arguments", "sequence() is a more general facility for generating sequences", "numerical vectors are generated by conditions"],
    correctAnswer: 0
  },
  {
    question: "Which of the following finds the position of a quantile in a dataset?",
    options: ["quantile()", "barplot()", "barchart()", "rep()"],
    correctAnswer: 0
  },
  {
    question: "Which of the following code create n samples of size “size” with probability prob from the binomial?",
    options: ["z <- rinom(n,size,pro)", "z <- rbinom(n,size,pro)", "z <- binom(n,size,pro)", "z >- nom(n,size,pro)"],
    correctAnswer: 1
  },
  {
    question: "What is the simplest way of creating the vector?",
    options: ["C function", "Create", "Destroy", "Invalid"],
    correctAnswer: 0
  },
  {
    question: "Which function replicates elements of vectors?",
    options: ["C", "Rep", "Crep", "Grep"],
    correctAnswer: 1
  },
  {
    question: "To bind a row onto an already existing matrix, the ______ function can be used.",
    options: ["rbind", "Sbnd", "Gbind", "Sbind"],
    correctAnswer: 0
  },
  {
    question: "Which of the following extracts first element of the vector x?",
    options: ["x[10]", "x[1]", "x[0]", "x[2]"],
    correctAnswer: 1
  },
  {
    question: "Two vectors N1 and N2 are defined as N1 = c(3, 2, 4) and N2 = c(1, 2). What will be the output of vector Z that is defined as N1*N2.",
    options: ["(3, 2, 4)", "(3, 6, 4)", "(3, 4, 5)", "(3, 4, 4)"],
    correctAnswer: 3
  },
  {
    question: "__________ can contain heterogeneous inputs.",
    options: ["Matrix", "Data Frames", "Matrix and Data Frames", "Does not exists"],
    correctAnswer: 1
  },
  {
    question: "R is mostly used in ______________",
    options: ["Problem solving", "Statistics", "Probability", "All of the mentioned"],
    correctAnswer: 3
  },
  {
    question: "What is the meaning of “<-”?",
    options: ["Functions", "Loops", "Addition", "Assignment"],
    correctAnswer: 3
  },
  {
    question: "In the expression x <- 4 in R, what is the class of ‘x’ as determined by the `class()’ function?",
    options: ["Character", "Numeric", "Integer", "Word"],
    correctAnswer: 2
  },
  {
    question: "Accessing elements is achieved through a process called ________",
    options: ["Indexing", "Outdexing", "Highlighting", "Scrapping"],
    correctAnswer: 0
  },
  {
    question: "Which function can be used to determine the names assigned to a list?",
    options: ["Names", "Name", "Nam", "Nem"],
    correctAnswer: 0
  },
  {
    question: "Joining two lists can be achieved either using the _________ function.",
    options: ["Concat", "Join", "Reduce", "Delete"],
    correctAnswer: 0
  },
  {
    question: "Which of the following simple the square root of σ square?",
    options: ["Variance", "Standard deviation", "Mean", "Median"],
    correctAnswer: 1
  },
  {
    question: "The abbreviation of Cumulative Distributive Function is ________",
    options: ["CDFN", "CMDF", "CMD", "CDF"],
    correctAnswer: 3
  },
  {
    question: "The corresponding R function for the CDF is __________",
    options: ["Dbinom", "Pbinom", "Cbinorm", "Hbinorm"],
    correctAnswer: 1
  },
  {
    question: "The associated R function is dlogis (x, location = 0, scale = 1) is for _________ distribution.",
    options: ["Logistic", "Linear", "Discrete", "Beta"],
    correctAnswer: 0
  },
  {
    question: "Which loop executes a sequence of statements multiple times and abbreviates the code that manages the loop variable?",
    options: ["for", "while", "do-while", "repeat"],
    correctAnswer: 3
  },
  {
    question: "Which of the following true about for loop?",
    options: ["Repeats a statement or group of statements while a given condition is true. It tests the condition before executing the loop body.", "it tests the condition at the end of the loop body.", "Both A and B", "None of the above"],
    correctAnswer: 1
  },
  {
    question: "In which statement terminates the loop statement and transfers execution to the statement immediately following the loop?",
    options: ["goto", "switch", "break", "label"],
    correctAnswer: 2
  },
  {
    question: "Data analytics is a discipline that does not includes",
    options: ["Collecting", "Cleansing", "Organizing", "Sharing"],
    correctAnswer: 3
  },
  {
    question: "EXCEL file is example of ______",
    options: ["Structured data", "Semi-structured data", "Unstructured data.", "Mixture of options A,B, AND C"],
    correctAnswer: 0
  },
  {
    question: "Descriptive analytics have ____ complexity.",
    options: ["Very high", "High", "Low", "None of these"],
    correctAnswer: 2
  },
  {
    question: "Prescriptive analytics have ____ value .",
    options: ["Foresight", "Insight", "Hindsight", "Insight & Hindsight"],
    correctAnswer: 0
  },
  {
    question: "Why were Q2 sales less than Q1 sales? is the example of which type of analytics?",
    options: ["Descriptive analytics", "Diagnostic analytics", "Predictive analytics", "Prescriptive analytics"],
    correctAnswer: 1
  },
  {
    question: "What will be the patient survival rate if Drug B is controlled instead of Drug A? is the example of which type of analytics?",
    options: ["Descriptive analytics", "Diagnostic analytics", "Predictive analytics", "Prescriptive analytics"],
    correctAnswer: 2
  },
  {
    question: "Prescriptive analytics build upon the results of ______analytics by prescribing actions that should be taken.",
    options: ["Descriptive analytics", "Diagnostic analytics", "Predictive analytics", "Business Inelegance"],
    correctAnswer: 2
  },
  {
    question: "Drill-down refers to the process of viewing data at a level of _____detail.",
    options: ["Decreased", "Increased", "Standard", "Reverse"],
    correctAnswer: 1
  },
  {
    question: "_____ a process of extracting and discovering patterns in large data sets",
    options: ["Process mining", "Database system", "Data mining", "BI"],
    correctAnswer: 2
  },
  {
    question: "JSON file is example of ______",
    options: ["Structured data", "Semi-structured data", "Unstructured data.", "Mixture of options A,B, AND C"],
    correctAnswer: 1
  },
  {
    question: "Social media is example of ______",
    options: ["Structured data", "Semi-structured data", "Unstructured data.", "Mixture of options A,B, AND C"],
    correctAnswer: 2
  },
  {
    question: "XML file is example of ______",
    options: ["Structured data", "Semi-structured data", "Unstructured data.", "Mixture of options A,B, AND C"],
    correctAnswer: 1
  },
  {
    question: "Full Form of JSON",
    options: ["JAVA Script Of Notation", "JAVA Script Object Notation", "JAVA Script Object Note", "Java Source Object Notation"],
    correctAnswer: 1
  },
  {
    question: "Which function is use to count root nodes in XML",
    options: ["xmlSize()", "Size()", "Count()", "None of these"],
    correctAnswer: 0
  },
  {
    question: "Which symbol is use to extract column of dataframe emp?",
    options: ["emp$", "emp#", "emp-", "emp!"],
    correctAnswer: 0
  },
  {
    question: "Select correct ans to Extract 3rd and 5th row with 2nd and 4th column from data frame emp",
    options: ["emp.data[c(2,4),c(3,5)]", "emp.data[(3,5),(2,4)]", "emp.data[3,5,2,4]", "emp.data[c(3,5),c(2,4)]"],
    correctAnswer: 3
  },
  {
    question: "Which function is use give date?",
    options: ["toDate()", "fromDate()", "as.date()", "None of these"],
    correctAnswer: 2
  },
  {
    question: "______ is used to give description of x-axis.",
    options: ["Xname", "xDescription", "xFactor", "xlab"],
    correctAnswer: 3
  },
  {
    question: "_____ is use to save the graph.",
    options: ["dev()", "dev.off()", "graph.off()", "None of these"],
    correctAnswer: 1
  },
  {
    question: "Which function is use to download webpage in R?",
    options: ["gatherLink()", "getHTMLLinks()", "getLinks()", "putlinks()"],
    correctAnswer: 1
  },
  {
    question: "To send query in Database ____ function is used.",
    options: ["dbSendQuery()", "Querysend()", "DbQuery()", "QueryDB()"],
    correctAnswer: 0
  },
  {
    question: "which package is use to read excel file in R?",
    options: ["readxl", "readexcel", "readline", "None of these"],
    correctAnswer: 0
  },
  {
    question: "Full form of CSV",
    options: ["comma sepreted values", "comma seprated vector", "common special value", "common specified value"],
    correctAnswer: 0
  },
  {
    question: "Full form of XML",
    options: [" extensible mark language.", " ext markup language.", " extensible markup language.", "None of these"],
    correctAnswer: 2
  },
  {
    question: "_____represents data in rectangular bars with length of the bar proportional to the value of the variable.",
    options: ["boxplot", "histogram", "piechart", "barchart"],
    correctAnswer: 3
  },
  {
    question: "Which parameter is use to give name of bars on x axis in bar chart ?",
    options: ["name.args", "names.arg", "name.arg", "names.args"],
    correctAnswer: 1
  },
  {
    question: "Which function is used in program to save file in graph program?",
    options: ["dev.off()", "save", "ctrl+s", "None of these"],
    correctAnswer: 0
  },
  {
    question: "Which command is used to see current working directory path ?",
    options: ["getwds()", "getwd()", "gets()", "None of these"],
    correctAnswer: 1
  },
  {
    question: "Which command is used to set working directory path ?",
    options: ["setwd()", "setwds()", "sets()", "None of these"],
    correctAnswer: 0
  },
  {
    question: "Which package is use to deal with JSON file in R?",
    options: ["rjson", "RJSON", "RJson", "Rjson"],
    correctAnswer: 0
  },
  {
    question: "Which fuction is used to convert json object into data frame?",
    options: ["as.data.frame()", "to.data.frame", "both", "None of these"],
    correctAnswer: 0
  },
  {
    question: "_______graph that connects a series of points by drawing line segments between them.",
    options: ["line graph", "histogram", "piechart", "barchart"],
    correctAnswer: 0
  },
  {
    question: "______function in R is used to create the Scatter graph.",
    options: ["line()", "plot()", "lineplot()", "None"],
    correctAnswer: 1
  },
  {
    question: "Which parameter is used to set the limits of the values of x used for plotting?",
    options: ["xlim", "Xlim", "limit", "end"],
    correctAnswer: 0
  },
  {
    question: "Which is used when we have more than two variables and we want to find the correlation between onevariable versus the remaining ones",
    options: ["Scatterplot matrix", "matrix", "multi correlation", "regression"],
    correctAnswer: 0
  },
  {
    question: "_____visual representation of the statistical five number summary of a given data set.",
    options: ["barplot", "boxplot", "lineplot", "None of these"],
    correctAnswer: 1
  },
  {
    question: "Which is not covered in five number summary?",
    options: ["Mean", "first quartile", "third quartile", "median"],
    correctAnswer: 0
  },
  {
    question: "Full form of IQR",
    options: ["inter quartile range", "inter qaud range", "Inter quartile residual", "None"],
    correctAnswer: 0
  },
  {
    question: "Which function is used to draw histogram in R?",
    options: ["histogram()", "hist()", "histo()", "None"],
    correctAnswer: 1
  },
  {
    question: "Full form of sd()",
    options: ["standard deviation", "semi daviation", "some deligation", "none of theese"],
    correctAnswer: 0
  },
  {
    question: "What is square root of variance ?",
    options: ["Standard deviation", "MAD", "Median", "none of theese"],
    correctAnswer: 0
  },
  {
    question: "What is square of standard deviation?",
    options: ["standard deviation", "variance", "mean", "none of theese"],
    correctAnswer: 1
  },
  {
    question: "Full form of ANOVA",
    options: ["Analysis of variable", "Analysis of variance", "Analyse variance", "Accurate Variance"],
    correctAnswer: 1
  },
  {
    question: "Mean of 1,2,3,4,5 is_____",
    options: ["3", "3.5", "4.5", "none of theese"],
    correctAnswer: 0
  },
  {
    question: "Mode of 9,3,1,8,3,6,3 is_____",
    options: ["3", "1", "9", "4.5"],
    correctAnswer: 0
  },
  {
    question: "Range of 9,3,1,8,3,6,3 is_____",
    options: ["1", "8", "9", "7"],
    correctAnswer: 1
  },
  {
    question: "R function to find varianace",
    options: ["var()", "variance()", "V()", "None"],
    correctAnswer: 0
  },
  {
    question: "R function to find Standard daviation",
    options: ["sd()", "std()", "s.d()", "None"],
    correctAnswer: 0
  },
  {
    question: "Which of these is not measure of central tendency ?",
    options: ["mean", "range", "mode", "median"],
    correctAnswer: 1
  },
  {
    question: "Which of these is measure of variablity?",
    options: ["mean", "range", "mode", "median"],
    correctAnswer: 1
  },
  {
    question: "Which of these is not measure of variablity?",
    options: ["variance", "range", "mode", "standard deviation"],
    correctAnswer: 2
  },
  {
    question: "Median is measure of _____",
    options: ["central tendancy", "variablity", "both", "none"],
    correctAnswer: 0
  },
  {
    question: "Variance is measure of _____",
    options: ["central tendancy", "variablity", "both", "none"],
    correctAnswer: 1
  },
  {
    question: "Range means_____",
    options: ["small-large", "large-small", "large", "small"],
    correctAnswer: 1
  },
  {
    question: "Which function will give probabilty of one point ?",
    options: ["dnorm()", "pnorm()", "qnorm()", "None"],
    correctAnswer: 0
  },
  {
    question: "Which function will give probabilty of more point(cummulative) ?",
    options: ["dnorm()", "pnorm()", "qnorm()", "None"],
    correctAnswer: 1
  },
  {
    question: "Which function is used to find probability in Binomial distribution?",
    options: ["dbinom()", "db()", "dbinomial()", "None"],
    correctAnswer: 0
  },
  {
    question: "Which function is used to find probability in Norm distribution?",
    options: ["dnorm()", "dn()", "Dnormal()", "None"],
    correctAnswer: 0
  },
  {
    question: "Which method is used to determine difference between several samples?",
    options: ["ANOVA", "MOVA", "MEAN", "REGRESSION"],
    correctAnswer: 0
  },
  {
    question: "Which function is used in R for ANOVA",
    options: ["aov()", "Anov()", "ANOV()", "None"],
    correctAnswer: 0
  },
  {
    question: "Which R function is used to find linear regression line ?",
    options: ["lr()", "lm()", "linr()", "None"],
    correctAnswer: 1
  },
  {
    question: "Which is extension of linear regression",
    options: ["multiple regression", "mean regression", "both", "None"],
    correctAnswer: 0
  },
  {
    question: "Which R function is used to find logistic regression line ?",
    options: ["glm()", "gm()", "lm()", "None"],
    correctAnswer: 0
  },
  {
    question: "Which package is required for decision tree?",
    options: ["party", "rpart", "both", "None of these"],
    correctAnswer: 2
  },
  {
    question: "Which R function is used to classification and regression decision tree?",
    options: ["tr", "ctree", "tree", "mtree"],
    correctAnswer: 1
  },
  {
    question: "____ is a series of data points in which each data poinys is connected with a time stamp",
    options: ["Time series", "cycle series", "tree", "node tree"],
    correctAnswer: 0
  },
  {
    question: "Which R function is used to make time series?",
    options: ["ts()", "times()", "tseries()", "None of these"],
    correctAnswer: 0
  },
  {
    question: "Which is used to analyse prediction the time when specific event is going to occur?",
    options: ["Time series", "Survival analysis", "Tree", "None of these"],
    correctAnswer: 1
  },
  {
    question: "Which package is required to carried out survival analysis?",
    options: ["survival", "surv", "sa", "None of these"],
    correctAnswer: 0
  },
  {
    question: "Which R function is used to create survival object?",
    options: ["Surv()", "survival()", "surf()", "None of these"],
    correctAnswer: 0
  },
  {
    question: "Which R function is used to create plot of survival analysis?",
    options: ["survfit()", "survplot()", "line()", "None of these"],
    correctAnswer: 0
  }
];
